###
 # FP-UNA
 # Lenguajes de Programacion 3 2019
 # Makefile Capitulo 2 
 #Integrantes:
 #@Miryam Godoy
 #@Alex Gomez
###
PROGRAMS: arglist client getopt_long print-env

.PHONY: all clean

#Destino predeterminado: construir todo
all: $(PROGRAMS)

#Limpiar los productos de construccion
clean:
	rm -f *.o *.a $(PROGRAMS)
